//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialExamV3.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialExamV3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///材料类试题学习
        ///试题总数: 652	单选题数: 196	多选题数: 54	判断题数: 402
        ///一 单选题 （ 196道 ）
        ///1 、电击（触电）通常指因为人体接触带电的供电线路或设备而受到伤害的事故。为了避免电击（触电）事故的发生，请判断下列措施正确的是
        ///A、设备可靠接地而人体对地绝缘	B、设备和人体都可靠接地	C、设备和人体都对地绝缘	D、设备对地绝缘而人体可靠接地
        ///标准答案： A
        ///答案解析：
        ///2 、&quot;在需要带电操作的低电压电路实验时，下列哪种是正确的？
        ///A、双手操作比单手操作安全	B、单手操作比双手操作安全	C、单手操作和双手操作一样安全	D、操作与空气湿度有关
        ///标准答案： B
        ///答案解析：
        ///3 、下列哪种物质与乙醇混溶时易发生爆炸
        ///A、盐酸	B、乙醚	C、高氯酸	D、丙酮
        ///标准答案： C
        ///答案解析：
        ///4 、存放剧毒物品必须使用（）保管、储存。
        ///A、带锁的铁皮柜	B、铁皮柜	C、带双锁的铁皮保险柜
        ///标准答案： C
        ///答案解析：
        ///5 、Cl2和CO作用生成的光气毒性比Cl2
        ///A、小	B、大
        ///标准答案： B
        ///答案解析：
        ///6 、为了防止在开启或关闭玻璃容器时发生危 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
    }
}
